serverAddr = "SERVER_HOST"
serverPort = SERVER_PORT
auth.token = "AUTH_TOKEN"

[[proxies]]
name = "blog_root"
type = "http"
localPort = 80
customDomains = ["ROOT_DOMAIN_NAME"]
transport.proxyProtocolVersion = "v2"
remotePort = 33514

[[proxies]]
name = "ilaipi"
type = "http"
localPort = 80
customDomains = ["*.ROOT_DOMAIN_NAME"]
transport.proxyProtocolVersion = "v2"
remotePort = 33514
