bindPort = SERVER_PORT

vhostHTTPPort = REMOTE_HTTP_PORT
vhostHTTPSPort = REMOTE_HTTPS_PORT

webServer.addr = "FRP_DASHBOARD_ADDR"
webServer.port = FRP_DASHBOARD_PORT
webServer.user = "FRP_DASHBOARD_USERNAME"
webServer.password = "FRP_DASHBOARD_PASSWORD"


auth.token = "AUTH_TOKEN"
