name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Huawei Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: replace secrets
      run: |
        conf_file_name=frpc.toml
        cp ./frpc/$conf_file_name .
        sed -i 's/SERVER_HOST/${{ secrets.SERVER_HOST }}/g' $conf_file_name
        sed -i 's/SERVER_PORT/${{ secrets.SERVER_PORT }}/g' $conf_file_name
        sed -i 's/AUTH_TOKEN/${{ secrets.AUTH_TOKEN }}/g' $conf_file_name
        sed -i 's/ROOT_DOMAIN_NAME/${{ secrets.ROOT_DOMAIN_NAME }}/g' $conf_file_name
        
        conf_file_name=frps.toml
        cp ./frps/$conf_file_name .
        sed -i 's/SERVER_PORT/${{ secrets.SERVER_PORT }}/g' $conf_file_name
        sed -i 's/FRP_DASHBOARD_ADDR/${{ secrets.FRP_DASHBOARD_ADDR }}/g' $conf_file_name
        sed -i 's/FRP_DASHBOARD_PORT/${{ secrets.FRP_DASHBOARD_PORT }}/g' $conf_file_name
        sed -i 's/FRP_DASHBOARD_USERNAME/${{ secrets.FRP_DASHBOARD_USERNAME }}/g' $conf_file_name
        sed -i 's/FRP_DASHBOARD_PASSWORD/${{ secrets.FRP_DASHBOARD_PASSWORD }}/g' $conf_file_name
        sed -i 's/AUTH_TOKEN/${{ secrets.AUTH_TOKEN }}/g' $conf_file_name

    - name: Build and push Frpc
      uses: docker/build-push-action@v5
      with:
        context: ./frpc/
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_HUB_SPACE }}/${{ vars.DOCKER_IMAGE_NAME_FRPC }}:latest
        build-args: |
          FRP_VERSION=${{ vars.FRP_VERSION }}

    - name: Build and push Frps
      uses: docker/build-push-action@v5
      with:
        context: ./frps/
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_HUB_SPACE }}/${{ vars.DOCKER_IMAGE_NAME_FRPS }}:latest
        build-args: |
          FRP_VERSION=${{ vars.FRP_VERSION }}
